theme: mini
defaultContentLanguage: zh # en
title: taojy的技术博客

markup:
  highlight:
    guessSyntax: true
    style: monokai
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

params:
  author: "Taojy93"
  copyright: ' ' # 使用空格代替 copyright 显示
  showPowerBy: false
  hiddenPostSummaryInHomePage: true
  showToc: true